[package]
name = "youtube-takeout-to-watchmarker"
version = "0.1.0"
authors = ["JP Posma <j@npaulpos.ma>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
